#pragma once

// This file is automatically generated for your platform with cmake, please do not edit it manually

class FastnetmonPlatformConfigurtion {
    public:

    std::string fastnetmon_version = "1.2.10 c432c377";

    std::string pid_path = "/var/run/fastnetmon.pid";
    std::string global_config_path = "/etc/fastnetmon.conf";

    std::string log_file_path = "/var/log/fastnetmon.log";
    std::string attack_details_folder = "/var/log/fastnetmon_attacks";

    // Default path to notify script
    std::string notify_script_path = "/usr/local/bin/notify_about_attack.sh";

    // Default path to file with networks for whitelising
    std::string white_list_path = "/etc/networks_whitelist";

    // Default path to file with all networks listing
    std::string networks_list_path = "/etc/networks_list";

    // Path to temporarily store backtrace when fatal failure happened
    std::string backtrace_path = "/var/log/fastnetmon_backtrace.dump";

    // Path to whitelist rules
    std::string whitelist_rules_path = "/etc/whitelist_rules";
};
